#!/bin/bash
set -Eeuo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source_repository="$(realpath "${1:?Usage: install-gentoo.sh /path/to/generated/repository}")"
[ -f "$source_repository/.codex-desktop-generated" ] || { echo 'Not a generated codex-desktop repository' >&2; exit 1; }
manifest="$source_repository/app-misc/codex-desktop/Manifest"
payload="$(awk '$1 == "DIST" { print $2 }' "$manifest")"
[[ "$payload" =~ ^codex-desktop-[0-9.]+-(amd64|arm64)-payload-[0-9a-f]{64}\.tar\.xz$ ]] || { echo 'Invalid local payload name' >&2; exit 1; }
payload_source="$source_repository/../$payload"
[ -f "$payload_source" ] || { echo 'Missing local payload archive' >&2; exit 1; }

if [ "$(id -u)" -ne 0 ]; then
    exec "$SCRIPT_DIR/sudo-with-alert.sh" bash "$0" "$source_repository"
fi

repository=/var/db/repos/codex-desktop-local
config=/etc/portage/repos.conf/codex-desktop-local.conf
if [ -e "$repository" ] && [ ! -f "$repository/.codex-desktop-generated" ]; then
    echo "Refusing to overwrite unmanaged repository: $repository" >&2
    exit 1
fi
if [ -e "$config" ] && ! grep -Fxq '# Generated by codex-desktop-linux install-gentoo.sh' "$config"; then
    echo "Refusing to overwrite unmanaged config: $config" >&2
    exit 1
fi
for exe in /proc/[0-9]*/exe; do
    if [ "$(readlink "$exe" 2>/dev/null || true)" = /opt/codex-desktop/ChatGPT ]; then
        echo 'Exit the native ChatGPT Community before installing' >&2
        exit 1
    fi
done
mkdir -p /var/db/repos /etc/portage/repos.conf
distdir="$(portageq envvar DISTDIR)"
mkdir -p "$distdir"
if [ -e "$distdir/$payload" ]; then
    cmp "$payload_source" "$distdir/$payload" || { echo 'Conflicting existing distfile' >&2; exit 1; }
else
    install -m 0644 "$payload_source" "$distdir/$payload"
fi
staging="$(mktemp -d /var/db/repos/.codex-desktop-local.XXXXXX)"
trap 'rm -rf -- "$staging"' EXIT
cp -a --no-preserve=ownership "$source_repository/." "$staging/"
chown -R root:root "$staging"
chmod -R u=rwX,go=rX "$staging"
if [ -e "$repository" ]; then
    rm -rf -- "$repository"
fi
mv "$staging" "$repository"
printf '# Generated by codex-desktop-linux install-gentoo.sh\n[codex-desktop-local]\nlocation = /var/db/repos/codex-desktop-local\nmasters = gentoo\nauto-sync = no\n' > "$config"
chmod 0644 "$config"
ebuilds=("$repository"/app-misc/codex-desktop/*.ebuild)
[ "${#ebuilds[@]}" -eq 1 ] || { echo 'Expected exactly one generated ebuild' >&2; exit 1; }
version="${ebuilds[0]##*/codex-desktop-}"
version="${version%.ebuild}"
# Package-scoped policy, never a global ACCEPT_* override for dependencies.
for policy in package.accept_keywords package.license; do
    mkdir -p "/etc/portage/$policy"
    target="/etc/portage/$policy/codex-desktop-local"
    if [ -e "$target" ] && ! grep -Fxq '# Generated by codex-desktop-linux install-gentoo.sh' "$target"; then
        echo "Refusing to overwrite unmanaged policy: $target" >&2
        exit 1
    fi
    printf '# Generated by codex-desktop-linux install-gentoo.sh\n' > "$target"
    if [ "$policy" = package.accept_keywords ]; then
        printf 'app-misc/codex-desktop::codex-desktop-local ~%s\n' "$(portageq envvar ARCH)" >> "$target"
    else
        printf 'app-misc/codex-desktop::codex-desktop-local all-rights-reserved\n' >> "$target"
    fi
    chmod 0644 "$target"
done
exec emerge --usepkg=n --getbinpkg=n "=app-misc/codex-desktop-$version::codex-desktop-local"
